spring.application.name=Santax-PP
spring.datasource.url=jdbc:postgresql://localhost:5432/santax_db
spring.datasource.username=postgres
spring.datasource.password=2001

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
